fix
Change-Id: I6ec5d0587e6dbc90c564c3537336123cc4222d66

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,16 +35,21 @@ jobs:
       - name: get release version
         id: release_version
         run: |
-          TAGGED_VERSION="${GITHUB_REF/refs\/tags\/v/}""
-          WRITTEN_VERSION="$(cat package.json | jq '.version' -r)"
+          TAGGED_VERSION="${GITHUB_REF/refs\/tags\/v/}"
+          
+          if [[ ! "${TAGGED_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
+            echo "Invalid version tag '${TAGGED_VERSION}'"
+            exit 1
+          fi
 
           echo ::set-env name=EXT_VERSION::"${TAGGED_VERSION}"
-
+          WRITTEN_VERSION="$(cat package.json | jq '.version' -r)"
+          
           if [[ ${TAGGED_VERSION} == *"-"* ]]; then
             echo ::set-env name=EXT_ISPREVIEW::1
           else
             if [[ "${TAGGED_VERSION}" != "${WRITTEN_VERSION}" ]]; then
-              echo "Release Tag and Version in package.json do not match (${TAGGED_VERSION} vs ${WRITTEN_VERSION})"
+              echo "Release Tag and Version in package.json do not match: '${TAGGED_VERSION}' vs '${WRITTEN_VERSION}'"
               exit(1)
             fi
             echo ::set-env name=EXT_ISPREVIEW::0
